#!/bin/bash

# Read the last line of the file iacta
last_line=$(tail -n 1 iacta)

# Append the last line to the file iacta
echo "$last_line" >> iacta

# Print the contents of the file iacta
cat iacta
