#!/bin/bash

# Find all subdirectories in the current directory
subdirs=$(find . -type d)

# Set execute permission for owner, group owner, and all other users
for dir in $subdirs; do
  chmod a+x "$dir"
done
